### ISSUE TITLE
How do we use emit(..)?

### ISSUE THREAD

**Issue by sameera** [domiSchenk/PouchDB-typescript-definitions#4]
I'm trying to build a design doc as described in:
https://pouchdb.com/2014/05/01/secondary-indexes-have-landed-in-pouchdb.html

However, TS doesn't recognize the emit(..) method and d.ts file doesn't seem to have it declared. Is there a way to get around this?

**Comment by domiSchenk** [comment]
not right now.
you could use `declare var emit:any`
see here: http://stackoverflow.com/questions/26160028/using-a-3rd-party-js-file-with-typescript

**Comment by thiagobackadelino** [comment]
obtive o mesmo problema utilizando typescript e pouchdb , couchdb ao criar Persistent queries.
 como solução e levando em conta que não será o type script que executara a function e sim o couchdb 


![image](https://cloud.githubusercontent.com/assets/14223502/22002217/dd0823a0-dc28-11e6-89a1-4284dd319c35.png)
